### ISSUE TITLE
TypeError in checkpattern handling

### ISSUE THREAD

**Issue by mweinelt** [freenode/Sigyn#40]
Probably related to the Python3 migration?

```pytb
ERROR 2018-10-28T14:50:40 Spec: [<context for owner>, <context for text>]
ERROR 2018-10-28T14:50:40 Received args: []
ERROR 2018-10-28T14:50:40 Extra args: ['text']
ERROR 2018-10-28T14:50:40 Uncaught exception in ['checkpattern'].
Traceback (most recent call last):
  File "/home/sigyn/.local/lib/python3.5/site-packages/supybot/callbacks.py", line 1320, in _callCommand
    self.callCommand(command, irc, msg, *args, **kwargs)
  File "/home/sigyn/.local/lib/python3.5/site-packages/supybot/utils/python.py", line 90, in g
    f(self, *args, **kwargs)
  File "/home/sigyn/.local/lib/python3.5/site-packages/supybot/callbacks.py", line 1286, in callCommand
    method(irc, msg, *args, **kwargs)
  File "/home/sigyn/.local/lib/python3.5/site-packages/supybot/commands.py", line 1093, in newf
    f(self, irc, msg, args, *state.args, **state.kwargs)
  File "/home/sigyn/config/plugins/Sigyn/plugin.py", line 658, in checkpattern
    self.log.info('%s : %s (%s)' % (pattern.uid,text,pattern.match(text)))
  File "/home/sigyn/config/plugins/Sigyn/plugin.py", line 365, in match
    s = self.pattern in text
TypeError: a bytes-like object is required, not 'str'
ERROR 2018-10-28T14:50:40 Exception id: 0x7c545
```

**Comment by ncoevoet** [comment]
Hi
i never got that error after the migration, is the pattern containing some weired chars ?

**Comment by mweinelt** [comment]
```
14:49 <+ADMIN> .addpattern 0 900 ATTN: This channel has moved to irc.freenode.net
14:49 <Sigyn> PATTERN: ADMIN added #27 : "attn: this channel has moved to irc.freenode.net" 0/900s                                                                                                                                 
14:49 <Sigyn> ADMIN: #27 added
14:50 <+ADMIN> .checkpattern  /!\ ATTN: This channel has moved to irc.freenode.net #/join /!\                                                                                                                                      
14:50 <Sigyn> ADMIN: An error has occurred and has been logged. Check the logs for more information.
```
